object Versions {
    const val coreKtx = "1.9.0"
    const val lifecycleRuntimeKtx = "2.7.0"
    const val activityCompose = "1.8.2"
    const val composeBom = "2023.03.00"
    const val composeNavigation = "2.7.6"
    const val composeMaterial3 = "1.1.2"
    const val Junit4 = "4.13.2"
    const val appCompat = "1.6.1"
    const val material = "1.8.0"
    const val hilt = "2.44"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val moshi = "1.14.0"
    const val coroutines = "1.3.9"
    const val splashScreen = "1.0.0"
    const val coil = "2.5.0"
}